import mysql.connector as sqltor
#mysql-python connection
mycon=sqltor.connect(host="localhost",user="root",passwd="1234",database="divya")
#cursorobject
cursor=mycon.cursor()
cursor.execute("create table user_password_database (UserID char(20) primary key, Password int)")
mycon.commit()
cursor.execute("create table doctors_info_database (Name char(20), Address char(50), Gender char(1), Age int, Joined date, Experience int, Specialisation char(20), Availability char(1))")
mycon.commit()
cursor.execute("create table patients_database (Name char(20), Address char(50), Age int, Gender char(1), covid char(1))")
mycon.commit()
cursor.execute("insert into user_password_database values('{}','{}')".format('Divya@ojha',619837778))
mycon.commit()
cursor.execute("insert into user_password_database values('{}','{}')".format('Bharati@1',294842095))
mycon.commit()
cursor.execute("insert into user_password_database values('{}','{}')".format('Gunjan2@1',665191753))
mycon.commit()
cursor.execute("insert into patients_database values('{}','{}','{}','{}','{}')".format('Rakesh Sharma','House no. 11, Anand Vihar',33,'M','y'))
mycon.commit()
cursor.execute("insert into patients_database values('{}','{}','{}','{}','{}')".format('Deepti Singh','22/7 Edison road',27,'F','y'))
mycon.commit()
cursor.execute("insert into patients_database values('{}','{}','{}','{}','{}')".format('Akshara Das','11/3 Radhe Shyam Colony',25,'F','n'))
mycon.commit()
cursor.execute("insert into doctors_info_database (Name, address, Gender, Age, Joined, Experience, Specialisation, Availability) values('{}', '{}', '{}', {}, '{}', {}, '{}', '{}')".format('Amit Kumar','29th street,M.G. road','M',40,'2006-03-22',17,'Cardiologist','y'))
mycon.commit()
cursor.execute("insert into doctors_info_database (Name, address, Gender, Age, Joined, Experience, Specialisation, Availability) values('{}', '{}', '{}', {}, '{}', {}, '{}', '{}')".format('Gunjan Singh', 'House no. 2,M.G. road', 'F', 45, '2004-09-14', 20, 'Anesthesiologist', 'y'))
mycon.commit()
cursor.execute("insert into doctors_info_database (Name, address, Gender, Age, Joined, Experience, Specialisation, Availability) values('{}', '{}', '{}', {}, '{}', {}, '{}', '{}')" .format('Sunita Nath','3 Block,J.K. road','F',44,'2011-03-20',11,'Immunologist','n'))
mycon.commit()
cursor.execute("insert into doctors_info_database (Name, address, Gender, Age, Joined, Experience, Specialisation, Availability) values('{}', '{}', '{}', {}, '{}', {}, '{}', '{}')" .format('Sunita Pandey','3/22, central avenue','F',46,'2010-09-21',12,'Neurologist','y'))
mycon.commit()
cursor.execute("create table staffs_info_database (Name char(20), Address char(50), Gender char(1), Age int, joined date, experience int, availability char(1))")
mycon.commit()
cursor.execute("insert into staffs_info_database (Name, address, Gender, Age, Joined, Experience, Availability) values('{}', '{}', '{}', {}, '{}', {}, '{}')".format('Ramu','56,Street','M',50,'2003-12-06',25,'y'))
mycon.commit()
cursor.execute("insert into staffs_info_database (Name, address, Gender, Age, Joined, Experience, Availability) values('{}', '{}', '{}', {}, '{}', {}, '{}')".format('Hari','46,Street','M',50,'2003-12-06',25,'n'))
mycon.commit()
print("Done")
